# Generated by Django 5.1.3 on 2026-03-11 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                ("dni", models.CharField(max_length=13, unique=True)),
                (
                    "birthday",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="Fecha de Nacimiento",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("male", "Masculino"), ("female", "Femenino")],
                        default="male",
                        max_length=10,
                        verbose_name="Sexo",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["id"],
            },
        ),
    ]
