# Generated by Django 6.0.3 on 2026-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_category_alter_client_sexo_product_sale_saledetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="desc",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Descripcion"
            ),
        ),
    ]
